/**
 * Semantic asset slots. Components never hardcode file paths — swap real art
 * in by replacing a placeholder file 1:1 (same name and aspect ratio) or by
 * repointing one line here. Placeholders are regenerated by
 * `node scripts/generate-placeholders.mjs`.
 */
import backdropWall from './placeholders/backdrop-wall.svg';
import dieNpc1 from './placeholders/die-npc-1.svg';
import dieNpc2 from './placeholders/die-npc-2.svg';
import dieNpc3 from './placeholders/die-npc-3.svg';
import dieNpc4 from './placeholders/die-npc-4.svg';
import diePlayer1 from './placeholders/die-player-1.svg';
import diePlayer2 from './placeholders/die-player-2.svg';
import diePlayer3 from './placeholders/die-player-3.svg';
import diePlayer4 from './placeholders/die-player-4.svg';
import handCupped from './placeholders/hand-cupped.svg';
import handOpen from './placeholders/hand-open.svg';
import npc0Accusing from './placeholders/npc-variant-0-accusing.svg';
import npc0Seated from './placeholders/npc-variant-0-seated.svg';
import npc1Accusing from './placeholders/npc-variant-1-accusing.svg';
import npc1Seated from './placeholders/npc-variant-1-seated.svg';
import npc2Accusing from './placeholders/npc-variant-2-accusing.svg';
import npc2Seated from './placeholders/npc-variant-2-seated.svg';
import npc3Accusing from './placeholders/npc-variant-3-accusing.svg';
import npc3Seated from './placeholders/npc-variant-3-seated.svg';
import pipLost from './placeholders/pip-lost.svg';
import pipNpc from './placeholders/pip-npc.svg';
import pipPlayer from './placeholders/pip-player.svg';
import splashTitle from './placeholders/splash-title.svg';
import tableSurface from './placeholders/table-surface.svg';
import type { Face } from '../api/types';

export interface NpcArt {
  seated: string;
  accusing: string;
}

export const assets = {
  backdrop: { wall: backdropWall },
  table: { surface: tableSurface },
  hand: { cupped: handCupped, open: handOpen },
  npcVariants: [
    { seated: npc0Seated, accusing: npc0Accusing },
    { seated: npc1Seated, accusing: npc1Accusing },
    { seated: npc2Seated, accusing: npc2Accusing },
    { seated: npc3Seated, accusing: npc3Accusing },
  ] satisfies NpcArt[],
  dice: {
    player: { 1: diePlayer1, 2: diePlayer2, 3: diePlayer3, 4: diePlayer4 },
    npc: { 1: dieNpc1, 2: dieNpc2, 3: dieNpc3, 4: dieNpc4 },
  } satisfies Record<'player' | 'npc', Record<Face, string>>,
  pips: { player: pipPlayer, npc: pipNpc, lost: pipLost },
  splash: { title: splashTitle },
} as const;

/** FNV-1a — stable, dependency-free portrait selection. Art variety only;
 * the engine's own seed hashing (name, traits) is unrelated. */
function fnv1a(text: string): number {
  let hash = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

export function npcArtForSeed(seed: string): NpcArt {
  const variant = fnv1a(seed) % assets.npcVariants.length;
  return assets.npcVariants[variant]!;
}
